# Generated by Django 3.0.2 on 2022-02-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0069_auto_20211128_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchmovie',
            name='search_original_title',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watchtvepisode',
            name='search_original_title',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watchtvseason',
            name='search_original_title',
            field=models.BooleanField(default=False),
        ),
    ]
