# Generated by Django 3.0.2 on 2022-02-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0070_auto_20220214_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchtvshow',
            name='search_original_title',
            field=models.BooleanField(default=False),
        ),
    ]
